apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashwini
spec:
  selector:
    matchLabels:
      key: one
  template:
    metadata:
      name: number
      labels:
        key: one
    spec:
      containers:
      - name: containerone
        image: tomcat
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: number
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ashwini
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
    key: one
  ports:
  - port: 80
    targetPort: 8080
    NodePort: 31000


